version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-bills-app:/var/lib/mysql
    env_file:
      - ../.env

volumes:
  db-bills-app:
    